# Generated by Django 5.1.2 on 2024-10-09 16:45

from django.db import migrations, models
from django.contrib.auth.models import User

type_map = {
    1: "Tea and Coffee",
    2: "Bakery",
    3: "Body Lotions",
    4: "Soaps",
    5: "Rice and Lentils",
    6: "Candies and Chocolates",
}


def create_types(apps, schema_editor):
    Type = apps.get_model("myapp", "Type")
    types = [
        "Tea and Coffee",
        "Bakery",
        "Body Lotions",
        "Soaps",
        "Rice and Lentils",
        "Candies and Chocolates",
    ]
    for type_name in types:
        Type.objects.create(name=type_name)


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_alter_client_city"),
    ]

    operations = [
        migrations.RunPython(create_types),
    ]
