# Generated by Django 5.1.2 on 2024-10-09 16:45

from django.db import migrations, models
from django.contrib.auth.models import User

type_map = {
    1: "Tea and Coffee",
    2: "Bakery",
    3: "Body Lotions",
    4: "Soaps",
    5: "Rice and Lentils",
    6: "Candies and Chocolates",
}

clients = [
    {
        "username": "usama",
        "interested_in": [1, 2, 3, 4, 5, 6],
    },
    {
        "username": "ziad",
        "interested_in": [1, 2, 3, 4],
    },
    {
        "username": "saja",
        "interested_in": [4, 5, 6],
    },
    {
        "username": "prashanth",
        "interested_in": [2, 4],
    },
    {
        "username": "mark",
        "interested_in": [3, 4, 6],
    },
]


def populate_interests(apps, schema_editor):
    Client = apps.get_model("myapp", "Client")
    Type = apps.get_model("myapp", "Type")

    for client_data in clients:
        client = Client.objects.get(username=client_data["username"])
        interests = Type.objects.filter(
            name__in=[type_map[type_id] for type_id in client_data["interested_in"]]
        )
        client.interested_in.set(interests)
        client.save()


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0005_create_users"),
    ]

    operations = [migrations.RunPython(populate_interests)]
