# Generated by Django 5.1.2 on 2024-10-09 16:45

from django.db import migrations, models
from django.contrib.auth.models import User


def populate_items_orders(apps, schema_editor):
    Type = apps.get_model("myapp", "Type")
    Item = apps.get_model("myapp", "Item")
    Client = apps.get_model("myapp", "Client")
    OrderItem = apps.get_model("myapp", "OrderItem")

    # Create or fetch Type objects
    tea_and_coffee, _ = Type.objects.get_or_create(name="Tea and Coffee")
    bakery, _ = Type.objects.get_or_create(name="Bakery")
    body_lotions, _ = Type.objects.get_or_create(name="Body Lotions")
    soaps, _ = Type.objects.get_or_create(name="Soaps")
    rice_and_lentils, _ = Type.objects.get_or_create(name="Rice and Lentils")
    candies_and_chocolates, _ = Type.objects.get_or_create(
        name="Candies and Chocolates"
    )

    # Create Item objects
    items_data = [
        ("Iced Tea", tea_and_coffee, 7.99, 100, True),
        ("Green Tea", tea_and_coffee, 5.54, 1500, True),
        ("Coffee", tea_and_coffee, 6.80, 2000, True),
        ("Handwash", soaps, 6.54, 0, False),
        ("Facewash", soaps, 9.50, 150, True),
        ("Jelly Beans", candies_and_chocolates, 3.99, 2700, True),
        ("Cadbury Milk Chocolate", candies_and_chocolates, 2.85, 1200, True),
        ("Nestle Butter Candies", candies_and_chocolates, 3.25, 0, False),
        ("Trident Gum", candies_and_chocolates, 1.99, 12, True),
        ("KitKat White Chocolate", candies_and_chocolates, 4.55, 1200, True),
        ("Basmati Rice", rice_and_lentils, 20.00, 50, True),
        ("Yellow Lentils", rice_and_lentils, 11.75, 28, True),
        ("Pizza", bakery, 12.50, 15, True),
        ("Cookies", bakery, 1.50, 250, True),
    ]

    for name, type_obj, price, stock, available in items_data:
        Item.objects.get_or_create(
            name=name, type=type_obj, price=price, stock=stock, available=available
        )

    # Fetch Clients
    client_usama = Client.objects.get(username="usama")
    client_prashanth = Client.objects.get(username="prashanth")
    client_mark = Client.objects.get(username="mark")

    # Fetch Items
    iced_tea = Item.objects.get(name="Iced Tea")
    pizza = Item.objects.get(name="Pizza")
    facewash = Item.objects.get(name="Facewash")
    trident_gum = Item.objects.get(name="Trident Gum")

    # Create OrderItem objects
    OrderItem.objects.get_or_create(
        item=iced_tea, client=client_usama, quantity=2, status=1
    )  # placed
    OrderItem.objects.get_or_create(
        item=pizza, client=client_usama, quantity=1, status=2
    )  # shipped
    OrderItem.objects.get_or_create(
        item=facewash, client=client_prashanth, quantity=2, status=0
    )  # cancelled
    OrderItem.objects.get_or_create(
        item=trident_gum, client=client_mark, quantity=6, status=3
    )  # delivered


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0006_populate_client_interests"),
    ]

    operations = [
        migrations.RunPython(populate_items_orders),
    ]
