# Generated by Django 5.1.2 on 2024-10-30 16:10

from django.db import migrations, models


def update_existing_lab_members(apps, schema_editor):
    LabMember = apps.get_model("myapp", "LabMember")
    members = [
        {
            "first_name": "Fwaad",
            "last_name": "Ahmad",
            "dob": "1980-01-01",
            "email": "fwaad@example.com",
            "gender": "M",
        },
        {
            "first_name": "Asif",
            "last_name": "Lohar",
            "dob": "1985-02-02",
            "email": "asif@example.com",
            "gender": "M",
        },
        {
            "first_name": "Mohammad",
            "last_name": "Abdullah",
            "dob": "1990-03-03",
            "email": "mohammad@example.com",
            "gender": "M",
        },
    ]
    for member in members:
        LabMember.objects.filter(
            first_name=member["first_name"], last_name=member["last_name"]
        ).update(dob=member["dob"], email=member["email"], gender=member["gender"])


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0008_labmember"),
    ]

    operations = [
        migrations.AddField(
            model_name="labmember",
            name="dob",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="labmember",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="labmember",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                max_length=1,
                null=True,
            ),
        ),
        migrations.RunPython(update_existing_lab_members),
    ]
